### ISSUE TITLE
May be worth adding Github LFS explanation

### ISSUE THREAD

**Issue by DamianPaniagua** [MasonStooksbury/Free-Games-V2#2]
Due to github LFS (Large File System) when I downloaded this via Zip the images in folders "GIFs" and "OCVTemplates" was not visible. It may be worth leaving a note that people should download via Github desktop or via command line.

**Comment by MasonStooksbury** [comment]
> Due to github LFS (Large File System) when I downloaded this via Zip the images in folders "GIFs" and "OCVTemplates" was not visible. It may be worth leaving a note that people should download via Github desktop or via command line.

Crap, I forgot LFS did that. Good catch, I'll resolve this in a sec. Thanks for your contribution!

**Comment by MasonStooksbury** [comment]
I untracked the PNG files the script needs and updated the README. Thanks again for your detective work and making these issues!
