### ISSUE TITLE
Will you add that the program closes itself?

### ISSUE THREAD

**Issue by Bukkake-crypto** [MasonStooksbury/Free-Games-V2#5]
Will you add that the program closes itself, just a little reminder and also if you want more popularity why not
make a video on youtube for that.

Wish you the greatest of luck

**Comment by MasonStooksbury** [comment]
Thanks for submitting an issue!

Frankly, I think it's pretty apparent that the script closes itself when it is finished, so I don't really feel a need to explicitly say this. But I'm opening to changing my mind if it comes up or appears to be a point of confusion
